# Generated by Django 6.0.6 on 2026-06-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('carrera', models.CharField(max_length=100)),
                ('semestre', models.IntegerField()),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
