# Generated by Django 6.0.6 on 2026-06-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiantes',
        ),
    ]
