# Generated by Django 6.0.6 on 2026-06-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=10)),
                ('dictamen_comite', models.TextField(blank=True, null=True)),
                ('monto_asignado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='estudiantes.estudiante')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='programas.programabeca')),
            ],
        ),
    ]
